[package]
name = 'Springcoin'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = '792c9c428b21bc21cee7e3a08231396571016592'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
spring_coin = "0xb00e9e309443456360395130e397cc8cb066308ef513532ffc2bb7f683b71f43"